---

- hosts: all
  become: true
  tasks:
  
  - name: Update (CentOS)
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Update (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all 
  become: true
  roles: 
  - node_exporter

- hosts: CT01 
  become: true
  vars: 
    target_ips:
      - "192.168.1.200:9100"
      - "192.168.1.201:9100"
      - "192.168.1.202:9100"
      - "192.168.1.203:9100"
      - "192.168.1.204:9100"
  roles: 
  - prometheus
  - grafana
 
